"""ans field add in testcase table

Revision ID: 3b5f9f1649f9
Revises: 787d9f834638
Create Date: 2023-03-05 19:07:27.569234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b5f9f1649f9'
down_revision = '787d9f834638'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testcases', sa.Column('ans', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testcases', 'ans')
    # ### end Alembic commands ###
