"""casbinpolicies table added

Revision ID: 4d008ac45934
Revises: 6c557878bb70
Create Date: 2023-03-02 09:52:35.428939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d008ac45934'
down_revision = '6c557878bb70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casbin_policies',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('ptype', sa.String(), nullable=True),
                    sa.Column('v0', sa.String(), nullable=True),
                    sa.Column('v1', sa.String(), nullable=True),
                    sa.Column('v2', sa.String(), nullable=True),
                    sa.Column('v3', sa.String(), nullable=True),
                    sa.Column('v4', sa.String(), nullable=True),
                    sa.Column('v5', sa.String(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=False),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_casbinpolicies_id'),
                    'casbin_policies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_casbinpolicies_id'), table_name='casbin_policies')
    op.drop_table('casbin_policies')
    # ### end Alembic commands ###
