"""Added account table

Revision ID: 566593b84f08
Revises: 4d008ac45934
Create Date: 2023-03-03 19:12:31.273855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566593b84f08'
down_revision = '4d008ac45934'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('casbin_rule')
    op.alter_column('casbin_policies', 'ptype',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('casbin_policies', 'v0',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('casbin_policies', 'v1',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('casbin_policies', 'v2',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('casbin_policies', 'v3',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('casbin_policies', 'v4',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('casbin_policies', 'v5',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_casbinpolicies_id', table_name='casbin_policies')
    op.create_index(op.f('ix_casbin_policies_id'), 'casbin_policies', ['id'], unique=True)
    op.add_column('users', sa.Column('pic', sa.String(), nullable=False,server_default="default.png"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pic')
    op.drop_index(op.f('ix_casbin_policies_id'), table_name='casbin_policies')
    op.create_index('ix_casbinpolicies_id', 'casbin_policies', ['id'], unique=False)
    op.alter_column('casbin_policies', 'v5',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('casbin_policies', 'v4',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('casbin_policies', 'v3',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('casbin_policies', 'v2',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('casbin_policies', 'v1',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('casbin_policies', 'v0',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('casbin_policies', 'ptype',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('casbin_rule',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ptype', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v0', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v1', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v2', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v3', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v4', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v5', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='casbin_rule_pkey')
    )
    # ### end Alembic commands ###
