"""Added account table

Revision ID: 7091af5d41b0
Revises: 3b5f9f1649f9
Create Date: 2023-03-06 11:08:03.369883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7091af5d41b0'
down_revision = '3b5f9f1649f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('questions_topics_topic_id_fkey', 'questions_topics', type_='foreignkey')
    op.create_foreign_key(None, 'questions_topics', 'topics', ['topic_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('testcases', sa.Column('testcase_value', sa.String(), nullable=False))
    op.drop_column('testcases', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testcases', sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('testcases', 'testcase_value')
    op.drop_constraint(None, 'questions_topics', type_='foreignkey')
    op.create_foreign_key('questions_topics_topic_id_fkey', 'questions_topics', 'scopes', ['topic_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
