"""name changed

Revision ID: 740b690f80cc
Revises: 7091af5d41b0
Create Date: 2023-03-06 13:17:56.091207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740b690f80cc'
down_revision = '7091af5d41b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testcases', sa.Column('value', sa.String(), nullable=False))
    op.drop_column('testcases', 'testcase_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testcases', sa.Column('testcase_value', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('testcases', 'value')
    # ### end Alembic commands ###
