"""question submission testcase answer topic enum  name changed

Revision ID: 787d9f834638
Revises: 46858f57429d
Create Date: 2023-03-05 18:29:57.448322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '787d9f834638'
down_revision = '46858f57429d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
